import type { TagId } from "@/content/tags";
import type { AllergenId } from "@/content/allergens";

export type MenuItem = {
    number?: number;
    name: string;
    price?: string;
    ingredients?: string[];
    tags?: TagId[];
    allergens?: AllergenId[];
};

export type MenuCategory = {
    id: string;
    title: string;
    note?: string;
    items: MenuItem[];
};

export type CategorizedMenu = {
    title: string;                // "Meny"
    categories: MenuCategory[];
};

export const pizzeriaMenu: CategorizedMenu = {
    title: "Meny",
    categories: [
        {
            id: "pizza-classic",
            title: "Pizzor kategori 1",
            note: "Note",
            items: [
                {
                    number: 1,
                    name: "Margherita",
                    price: "119 kr",
                    ingredients: ["ost"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 2,
                    name: "Vesuvio",
                    price: "119 kr",
                    ingredients: ["skinka"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 3,
                    name: "Capricciosa",
                    price: "119 kr",
                    ingredients: ["skinka", "champinjoner"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 4,
                    name: "Pepperoni",
                    price: "119 kr",
                    ingredients: ["pepperoni"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 5,
                    name: "Funghi",
                    price: "119 kr",
                    ingredients: ["champinjoner"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 6,
                    name: "Hawaii",
                    price: "119 kr",
                    ingredients: ["skinka", "ananas"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 7,
                    name: "Roma",
                    price: "119 kr",
                    ingredients: ["skinka", "lök"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 8,
                    name: "Vegetariana",
                    price: "119 kr",
                    ingredients: ["paprika", "lök"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 9,
                    name: "Napoli",
                    price: "119 kr",
                    ingredients: ["ansjovis"],
                    tags: ["fish"],
                    allergens: [],
                },
                {
                    number: 10,
                    name: "Salami",
                    price: "119 kr",
                    ingredients: ["salami"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 11,
                    name: "Quattro Formaggi",
                    price: "119 kr",
                    ingredients: ["mozzarella", "gorgonzola", "parmesan"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
            ],
        },

        {
            id: "pizza-premium",
            title: "Pizzor kategori 2",
            note: "note",
            items: [
                {
                    number: 11,
                    name: "Diavola",
                    price: "139 kr",
                    ingredients: ["salami piccante", "chili"],
                    tags: ["meat", "spicy"],
                    allergens: [],
                },
                {
                    number: 12,
                    name: "Quattro Formaggi Delux",
                    price: "139 kr",
                    ingredients: ["mozzarella", "gorgonzola", "parmesan", "pecorino"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 13,
                    name: "Parma",
                    price: "139 kr",
                    ingredients: ["parmaskinka", "ruccola", "parmesan"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 14,
                    name: "Venezia",
                    price: "139 kr",
                    ingredients: ["skinka", "champinjoner", "oliver"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 15,
                    name: "Calzone Classico",
                    price: "139 kr",
                    ingredients: ["skinka", "champinjoner", "lök"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 16,
                    name: "Vegetaria",
                    price: "139 kr",
                    ingredients: ["paprika", "zucchini", "aubergine"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 17,
                    name: "Milano",
                    price: "139 kr",
                    ingredients: ["salami", "lök", "paprika"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 18,
                    name: "Tonno",
                    price: "139 kr",
                    ingredients: ["tonfisk", "lök", "oliver"],
                    tags: ["fish"],
                    allergens: [],
                },
                {
                    number: 19,
                    name: "Pollo",
                    price: "139 kr",
                    ingredients: ["kyckling", "paprika", "curry"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 20,
                    name: "Greco",
                    price: "139 kr",
                    ingredients: ["fetaost", "oliver", "rödlök"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
            ],
        },

        {
            id: "pizza-delux",
            title: "Pizzor kategori 3",
            note: "note",
            items: [
                {
                    number: 21,
                    name: "Meatfiesta",
                    price: "159 kr",
                    ingredients: ["skinka", "köttfärs", "kyckling", "salami"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 22,
                    name: "Carnivora",
                    price: "159 kr",
                    ingredients: ["oxfilé", "bacon", "skinka", "lök"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 23,
                    name: "BBQ Chicken",
                    price: "159 kr",
                    ingredients: ["kyckling", "bacon", "rödlök", "bbq-sås"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 24,
                    name: "Inferno",
                    price: "159 kr",
                    ingredients: ["salami piccante", "pepperoni", "chili", "jalapeño"],
                    tags: ["meat", "spicy"],
                    allergens: [],
                },
                {
                    number: 25,
                    name: "Kebab Special",
                    price: "159 kr",
                    ingredients: ["kebabkött", "lök", "tomat", "feferoni"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 26,
                    name: "Ocean Deluxe",
                    price: "159 kr",
                    ingredients: ["räkor", "musslor", "tonfisk", "vitlök"],
                    tags: ["fish"],
                    allergens: [],
                },
                {
                    number: 27,
                    name: "Vegetariana Deluxe",
                    price: "159 kr",
                    ingredients: ["zucchini", "aubergine", "paprika", "champinjoner", "oliver"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 28,
                    name: "Parma Deluxe",
                    price: "159 kr",
                    ingredients: ["parmaskinka", "ruccola", "parmesan", "körsbärstomater"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 29,
                    name: "Gorgonzola Special",
                    price: "159 kr",
                    ingredients: ["oxfilé", "gorgonzola", "lök", "champinjoner"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 30,
                    name: "Mediterrana",
                    price: "159 kr",
                    ingredients: ["fetaost", "oliver", "soltorkade tomater", "ruccola"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
            ]
        },
        {
            id: "kebab",
            title: "Kebab",
            note: "note",
            items: [
                {
                    number: 31,
                    name: "Kebabtallrik",
                    price: "129 kr",
                    ingredients: ["kebab", "pommes", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 32,
                    name: "Kebabrulle",
                    price: "119 kr",
                    ingredients: ["bröd", "kebab", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 33,
                    name: "Kebab i pita",
                    price: "119 kr",
                    ingredients: ["pitabröd", "kebab", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 34,
                    name: "Kebab i bröd",
                    price: "109 kr",
                    ingredients: ["bröd", "kebab", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 35,
                    name: "Kycklingkebabtallrik",
                    price: "129 kr",
                    ingredients: ["kycklingkebab", "pommes", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 36,
                    name: "Kycklingkebabrulle",
                    price: "119 kr",
                    ingredients: ["bröd", "kycklingkebab", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 37,
                    name: "Kebabmix tallrik",
                    price: "139 kr",
                    ingredients: ["kebab", "kycklingkebab", "pommes", "sallad", "sås"],
                    tags: ["meat"],
                },
                {
                    number: 38,
                    name: "Falafeltallrik",
                    price: "119 kr",
                    ingredients: ["falafel", "pommes", "sallad", "sås"],
                    tags: ["vegetarian"],
                },
            ],
        },

        {
            id: "sallad",
            title: "Sallader",
            note: "note",
            items: [
                {
                    number: 39,
                    name: "Grekisk sallad",
                    price: "115 kr",
                    ingredients: ["sallad", "fetaost", "oliver"],
                    tags: ["vegetarian"],
                    allergens: ["milk"],
                },
                {
                    number: 40,
                    name: "Kycklingsallad",
                    price: "125 kr",
                    ingredients: ["sallad", "kyckling", "tomat", "gurka", "dressing"],
                    tags: ["meat"],
                    allergens: [],
                },
                {
                    number: 41,
                    name: "Räksallad",
                    price: "129 kr",
                    ingredients: ["sallad", "räkor", "ägg", "dressing"],
                    tags: ["fish"],
                    allergens: ["egg"],
                },
                {
                    number: 42,
                    name: "Tonfisksallad",
                    price: "125 kr",
                    ingredients: ["sallad", "tonfisk", "rödlök", "dressing"],
                    tags: ["fish"],
                    allergens: [],
                },
                {
                    number: 43,
                    name: "Mozzarellasallad",
                    price: "119 kr",
                    ingredients: ["sallad", "mozzarella", "tomat", "pesto"],
                    tags: ["vegetarian"],
                    allergens: ["milk"],
                },
                {
                    number: 44,
                    name: "Halloumisallad",
                    price: "125 kr",
                    ingredients: ["sallad", "halloumi", "tomat", "gurka", "dressing"],
                    tags: ["vegetarian"],
                    allergens: ["milk"],
                },
                {
                    number: 45,
                    name: "Avokadosallad",
                    price: "119 kr",
                    ingredients: ["sallad", "avokado", "tomat", "gurka"],
                    tags: ["vegetarian"],
                    allergens: [],
                },
                {
                    number: 46,
                    name: "Kebabsallad",
                    price: "125 kr",
                    ingredients: ["sallad", "kebab", "lök", "sås"],
                    tags: ["meat"],
                    allergens: [],
                },
            ],
        },

        {
            id: "burgare",
            title: "Burgare",
            note: "note",
            items: [
                {
                    number: 47,
                    name: "Cheeseburgare",
                    price: "119 kr",
                    ingredients: ["bröd", "burgare", "ost", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten", "milk"],
                },
                {
                    number: 48,
                    name: "Hamburgare",
                    price: "109 kr",
                    ingredients: ["bröd", "burgare", "sallad", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten"],
                },
                {
                    number: 49,
                    name: "Baconcheese",
                    price: "129 kr",
                    ingredients: ["bröd", "burgare", "bacon", "ost", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten", "milk"],
                },
                {
                    number: 50,
                    name: "Dubbelburgare",
                    price: "149 kr",
                    ingredients: ["bröd", "dubbel burgare", "ost", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten", "milk"],
                },
                {
                    number: 51,
                    name: "Chiliburgare",
                    price: "129 kr",
                    ingredients: ["bröd", "burgare", "jalapeño", "ost", "dressing"],
                    tags: ["meat", "spicy"],
                    allergens: ["gluten", "milk"],
                },
                {
                    number: 52,
                    name: "BBQ-burgare",
                    price: "129 kr",
                    ingredients: ["bröd", "burgare", "bacon", "bbq-sås", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten"],
                },
                {
                    number: 53,
                    name: "Kycklingburgare",
                    price: "129 kr",
                    ingredients: ["bröd", "kyckling", "sallad", "dressing"],
                    tags: ["meat"],
                    allergens: ["gluten"],
                },
                {
                    number: 54,
                    name: "Vegoburgare",
                    price: "129 kr",
                    ingredients: ["bröd", "vegoburgare", "sallad", "dressing"],
                    tags: ["vegetarian"],
                    allergens: ["gluten"],
                },
            ],
        },
        {
            id: "sauces",
            title: "Såser",
            note: "note",
            items: [
                {
                    name: "Mild sås",
                    price: "15 kr",
                    tags: [],
                    allergens: [],
                },
                {
                    name: "Stark sås",
                    price: "15 kr",
                    tags: ["spicy"],
                    allergens: [],
                },
                {
                    name: "Blandad sås",
                    price: "15 kr",
                    tags: [],
                    allergens: [],
                },
                {
                    name: "Vitlökssås",
                    price: "15 kr",
                    tags: [],
                    allergens: ["milk"],
                },
                {
                    name: "Bearnaisesås",
                    price: "20 kr",
                    tags: [],
                    allergens: ["egg", "milk"],
                },
                {
                    name: "Kebabsås",
                    price: "15 kr",
                    tags: [],
                    allergens: ["milk"],
                },
                {
                    name: "Chilisås",
                    price: "15 kr",
                    tags: ["spicy"],
                    allergens: [],
                },
                {
                    name: "BBQ-sås",
                    price: "15 kr",
                    tags: [],
                    allergens: [],
                },
            ],
        }
    ],
};
